@url_dev=http://localhost:3056/v1/api

### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json

{
    "name": "Shop 1asd232",
    "email": "ngbao08012ada312523003@gmail.com",
    "password": "abadadadadc"
}